### ISSUE TITLE
Configuration / compatibility?

### ISSUE THREAD

**Issue by PixelDog** [silverstripe/silverstripe-s3#13]
Is this compatible with CMS & Framework v4.0.0-beta3? I've defined following configuration values in mysite/_config.php:

AWS_REGION: The AWS region your S3 bucket is hosted in (e.g. eu-central-1)
AWS_BUCKET_NAME: The name of the S3 bucket to store assets in.
AWS_ACCESS_KEY_ID: Your AWS access key that has access to the bucket you want to access
AWS_SECRET_ACCESS_KEY

assets are still stored and referenced from the local assets, on the front end and in the content editor. I don't see anything going to S3. Am I missing a configuration value or any other step in setting this up?

**Comment by chillu** [comment]
Hmm, I've just installed it on 4.0.x-dev and it works like a charm. I've assigned an IAM role with S3 access to my EC2 instance instead of using explicit access key and secret configurations. But didn't have to configure anything else, was picked up automatically. I don't think anything changed since beta3 there, but could you try again please? Agree that we need a better way to determine if this has been set up correctly and is active (dev/build?)

**Comment by MightyMerio** [comment]
Any chance for a quick pointer?  I am not quite seeing where to add the config settings. Do they go in the top level .env file, or config yml or _config.php, and what would be the syntax?

**Comment by MightyMerio** [comment]
Solved this. I am using MAMP PRO. The env variables simply need to be added to the vhost in hosts tab.
<img width="514" alt="screen shot 2018-07-17 at 11 23 53 am" src="https://user-images.githubusercontent.com/34455069/42834413-086a3670-89b4-11e8-89e2-dfceea614d66.png">
